const darkColors = {
    background: '#1a1a1a',
    border: '#b2b2b2',
    primary: '#f2f2f2',
    secondary:'#d3d3d3',
    tertiary: '#999999',
    primaryBorder: '#dddddd',
    secondaryBorder: '#cccccc',
    grey: '#f2f2f2',
    sheetBorder: '#cccccc',
    red: '#ff3b3b',
    black: '#ffffff',
    focusedItem: 'white',
    shadow: '#1a1a1a',
    menuBorder: '#f2f2f2',
    menuBackground: '#1a1a1a',
    shadowBackground: '#000000',
    alwaysWhite: 'white',
    alwaysBlack: '#1a1a1a',
    errorBackground1: '#12295e',
    errorBackground2: '#0b1a3a',
    homeBackground1: "#12295e",
    homeBackground2: "#040a16",
    homeBackground3: "#0b1a3a",
    homeBackground4: "#000000",
    buttonGradientTop: '#29abe2',
    buttonGradientBottom: '#7f47dd',
    sheetGradientTop: '#333333',
    sheetGradientBottom: '#333333',
    editSheet:'#4d4d4d',
  };
  
  const colors = {
    background: 'white',
    border: '#b2b2b2',
    primary: '#4d4d4d',
    secondary:'#808080',
    tertiary: '#999999',
    primaryBorder: '#dddddd',
    secondaryBorder: '#b3b3b3',
    grey: '#f2f2f2',
    red: '#ff3b3b',
    black: '#1a1a1a',
    focusedItem: 'black',
    shadow: '#1a1a1a',
    menuBorder: '#fafafa',
    menuBackground: '#fafafa',
    shadowBackground: 'white',
     alwaysWhite: 'white',
     alwaysBlack: '#1a1a1a',
     errorBackground1: '#f09ca5',
     errorBackground2: '#f0c0c5',
     homeBackground1: 'white',
     homeBackground2: 'white',
     homeBackground3: 'white',
     homeBackground4: 'white',
     buttonGradientTop: 'black',
     buttonGradientBottom: 'black',
     sheetGradientTop: '#0A0A32',
     sheetGradientBottom: '#361682',
     editSheet:'#f2f2f2',
  };
  export default colors;
  