export const lightTheme = {
    background: 'white',
    border: '#b2b2b2',
    primary: '#4d4d4d',
    secondary:'#808080',
    tertiary: '#999999',
    primaryBorder: '#dddddd',
    secondaryBorder: '#b3b3b3',
    grey: '#f2f2f2',
    red: '#ff3b3b',
    black: '#1a1a1a',
    white: 'white',
    focusedItem: '#7ebcec',
    shadow: '#1a1a1a',
    menuBorder: '#fafafa',
    menuBackground: '#fafafa',
    shadowBackground: 'white',
     alwaysWhite: 'white',
     alwaysBlack: '#1a1a1a',
     errorBackground1: '#f09ca5',
     errorBackground2: '#f0c0c5',
     homeBackground1: 'white',
     homeBackground2: 'white',
     homeBackground3: 'white',
     homeBackground4: 'white',
     buttonGradientTop: 'black',
     buttonGradientBottom: 'black',
     sheetGradientTop: '#0A0A32',
     sheetGradientBottom: '#361682',
     editSheet:'#f2f2f2',
     glosarioCircles: ['#84cbe9', '#ae84e9', '#8ae6c6'],
     eventYellow: "#f7f18d",
     eventPink: "#e9b5e5",
     eventGreen:"#8ef7c4",
     eventPurple: "#ab89e9",
     eventBlue: "#7ebcec",
     eventMagenta: "#dd89e2",
     alertModal: 'white',
     alertButtons: '#FAFAFA',
     membresiaBeneficio: '#EDF7FF',
     membresiaBoton: '#7EBCEC',
     membresiaCancel: '#b3b3b3',
  };
  
  export const darkTheme = {
    background: '#1a1a1a',
    border: '#b2b2b2',
    primary: '#f2f2f2',
    secondary:'#d3d3d3',
    tertiary: '#999999',
    primaryBorder: '#999999',
    secondaryBorder: '#cccccc',
    grey: '#1a1a1a',
    sheetBorder: '#cccccc',
    red: '#ff3b3b',
    black: '#ffffff',
    white: 'black',
    focusedItem: '#7ebcec',
    shadow: '#1a1a1a',
    menuBorder: '#f2f2f2',
    menuBackground: '#1a1a1a',
    shadowBackground: '#000000',
    alwaysWhite: 'white',
    alwaysBlack: '#1a1a1a',
    errorBackground1: '#12295e',
    errorBackground2: '#0b1a3a',
    homeBackground1: "#12295e",
    homeBackground2: "#040a16",
    homeBackground3: "#0b1a3a",
    homeBackground4: "#000000",
    buttonGradientTop: '#29abe2',
    buttonGradientBottom: '#7f47dd',
    sheetGradientTop: '#333333',
    sheetGradientBottom: '#333333',
    editSheet:'#4d4d4d',
    glosarioCircles: ['#29ABE2', '#7629E2', '#29E2A1'],
    eventYellow: "#F8FF2E",
     eventPink: "#DD8BD9",
     eventGreen:"#4FF5A4",
     eventPurple: "#7F47DD",
     eventBlue: "#29ABE2",
     eventMagenta: "#E229DC",
     alertModal: '#4d4d4d',
     alertButtons: '#525252',
     membresiaBeneficio: '#1a1a1a',
     membresiaBoton: '#1a1a1a',
     membresiaCancel: '#1a1a1a',
  };